name: Dependency and Licence Nightly Checks

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  call-workflow:
    uses: studiographene/studiographene-nodejs-scans/.github/workflows/cron-ci.yml@master

    with:
      project_name: CI-SCANS
      apply_suppression: false

    permissions: write-all
